### ISSUE TITLE
Crash with some characters

### ISSUE THREAD

**Issue by C4illin** [Fabbbe/distractionless#3]
The program crashes when i try to save a document with "→" in it.

Crash Report
Traceback (most recent call last):
  File "main.py", line 125, in save_text_file
    save_file.write(text_to_save)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 0: character maps to <undefined>

**Comment by Fabbbe** [comment]
This issue isn't present on Linux

**Comment by Fabbbe** [comment]
It's now fully fixed!
